### ISSUE TITLE
非zip的svga文件会重复下载

### ISSUE THREAD

**Issue by lzh888777** [svga/SVGAPlayer-iOS#101]
* SVGAParser的 parseWithData:chaceKey:方法非zip的data没有保存在磁盘中.
* SVGAParser的 parseWithUrlRequest:方法 如果在磁盘中没有找到，就直接下载了，是否应该加一个SVGAVideoEntity的readCache操作，NSCache也没有找到再下载

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-iOS#cache

**Comment by heimu** [comment]
明明一直有bug ,ios一直不能缓存，为啥每次提issue都是你提这个地方呢？很奇怪。

**Comment by PonyCui** [comment]
Player 不会主动管理缓存，Player 依赖 NSURLSession 的缓存机制，具体可自行查阅相关文档。
如果需要强制缓存，可以自行传入相关 NSData 到 Parser 中。
