### ISSUE TITLE
2.5.0适配ios13的包可以上传一下吗？

### ISSUE THREAD

**Issue by 1275053499** [svga/SVGAPlayer-iOS#105]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by errnull** [comment]
Please see
#103 
https://github.com/yyued/SVGAPlayer-iOS/issues/103#issuecomment-558254397
