### ISSUE TITLE
pod version 2.3.5， can not  play svga animation on iOS 13.* . But perform well on iOS 12.*

### ISSUE THREAD

**Issue by iOScodeYF** [svga/SVGAPlayer-iOS#106]

**Comment by PonyCui** [comment]
Please provide a demo to reproduce your issue.
And the OS version, device info.

**Comment by iOScodeYF** [comment]
mac pro osVersion: 10.14.6  xcode version:11.2   iPhone: iphone 8  version 13.2.2
svga file:
[heartbeat.svga.zip](https://github.com/yyued/SVGAPlayer-iOS/files/3844994/heartbeat.svga.zip)
demo code:
`SVGAPlayer *player = [[SVGAPlayer alloc] initWithFrame:CGRectMake(0, 0, 200, 200)];
[self.view addSubview:player]; 
SVGAParser *parser = [[SVGAParser alloc] init];
[parser parseWithNamed:@"posche" inBundle:nil completionBlock:^(SVGAVideoEntity * _Nonnull videoItem) {
    if (videoItem != nil) {
        player.videoItem = videoItem;
        [player startAnimation];
    }
} failureBlock:nil];`

**Comment by Hanfang123** [comment]
me too，not play in ios13，ios12 is ok.

**Comment by Best199101** [comment]
Recently, we also received feedback from individual users. Have some animations been played? Has version 2.3.5 been solved?

**Comment by PonyCui** [comment]
I can not reproduce this issue on master branch, Xcode version Version 11.2.1 (11B500), iOS version 13.2.2 on iPhone X.
Are there any specific animation file?

**Comment by Hanfang123** [comment]
> me too，not play in ios13，ios12 is ok.

This problem was solved when I updated to version 2.3.5
