### ISSUE TITLE
SVGAAudioLayer 播放bug

### ISSUE THREAD

**Issue by michanMC** [svga/SVGAPlayer-iOS#110]
只[_audioPlayer prepareToPlay]; 不进行[_audioPlayer play]; 在demo正常播放，但在我实际的项目里并不能自动播放。建议[_audioPlayer prepareToPlay];后也调用[_audioPlayer play];
```
- (instancetype)initWithAudioItem:(SVGAAudioEntity *)audioItem videoItem:(SVGAVideoEntity *)videoItem
{
    self = [super init];
    if (self) {
        _audioItem = audioItem;
        if (audioItem.audioKey != nil && videoItem.audiosData[audioItem.audioKey] != nil) {

            _audioPlayer = [[AVAudioPlayer alloc] initWithData:videoItem.audiosData[audioItem.audioKey]
                                                  fileTypeHint:@"mp3"
                                                         error:NULL];
            [_audioPlayer prepareToPlay];
            [_audioPlayer play];

        }
    }
    return self;
}
```

**Comment by PonyCui** [comment]
是否可以提供 sample 文件呢？

**Comment by PonyCui** [comment]
@errnull 确实有必要添加 play 的调用

**Comment by michanMC** [comment]
我看了一下逻辑，我看到如果有多少个声源就创建多少个AVAudioPlayer，然后添加在数组里，然后在SVGAPlayer里update的进行play。但我项目有动画出现，没有声音
- (void)update {
    [CATransaction setDisableActions:YES];
    for (SVGAContentLayer *layer in self.contentLayers) {
        if ([layer isKindOfClass:[SVGAContentLayer class]]) {
            [layer stepToFrame:self.currentFrame];
        }
    }
    [CATransaction setDisableActions:NO];
    if (self.forwardAnimating && self.audioLayers.count > 0) {
        for (SVGAAudioLayer *layer in self.audioLayers) {
            if (!self.audioPlaying && layer.audioItem.startFrame >= self.currentFrame) {
                [layer.audioPlayer setCurrentTime:(NSTimeInterval)(layer.audioItem.startTime / 1000)];
                [layer.audioPlayer play];
                self.audioPlaying = YES;
            }
            if (self.audioPlaying && layer.audioItem.endFrame <= self.currentFrame) {
                [layer.audioPlayer stop];
                self.audioPlaying = NO;
            }
        }
    }
}

**Comment by errnull** [comment]
你好可以把相关的 svga 文件发到 help@svga.io 吗，
这边会尽快验证，svga 文件仅当测试使用。
@michanMC

**Comment by yangqingren** [comment]
fixed in 2.5.4
