### ISSUE TITLE
SVGAParser 在iOS13.3上是不是不能正常播放？12.X的就没有问题

### ISSUE THREAD

**Issue by chunnilzp** [svga/SVGAPlayer-iOS#115]
按照demo写的
    self.aPlayer = [[SVGAPlayer alloc] initWithFrame:CGRectMake(0, 0, 200, 200)];
    self.aPlayer.delegate = self;
    self.aPlayer.backgroundColor = [UIColor clearColor];
    [self.view addSubview:self.aPlayer]; 

     SVGAParser *parser = [[SVGAParser alloc] init];
    [parser parseWithNamed:@"kingset" inBundle:nil completionBlock:^(SVGAVideoEntity * _Nonnull videoItem) {
        if (videoItem != nil) {
            self.aPlayer.videoItem = videoItem;
            [self.aPlayer startAnimation];
        }
    } failureBlock:nil];
不会报任何错误，也能进入[self.aPlayer startAnimation]; 但就是无法播放，没有任何动画（在iOS13.3上），但是在iOS12上是可以播放的。

**Comment by PonyCui** [comment]
请使用 2.3.5 以上版本
