### ISSUE TITLE
GPU高播放卡顿

### ISSUE THREAD

**Issue by vviicc** [svga/SVGAPlayer-iOS#117]
用Instrument调试发现播放多个svga时，GPU很高（50%-80%），
`SVGAContentLayer stepToFrame:(NSInteger)frame self.mask = frameItem.maskLayer;` 发现这里比较耗时，近期有没有性能优化的版本？

**Comment by gdhGaoFei** [comment]
if ([SVGAVideoEntity isMP3Data:protoImages[key]]) {
                // mp3
                [audiosData setObject:protoImages[key] forKey:key];
            } else {
                UIImage *image = [[UIImage alloc] initWithData:protoImages[key] scale:2.0];
                if (image != nil) {
                    image = [image imageByResizeToSize:image.size];
                    [images setObject:image forKey:key];
                }
            }


- (UIImage *)imageByResizeToSize:(CGSize)size {
    if (size.width <= 0 || size.height <= 0) return nil;
    UIGraphicsBeginImageContextWithOptions(size, NO, self.scale);
    [self drawInRect:CGRectMake(0, 0, size.width, size.height)];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return image;
}

调用这个imageByResizeToSize方法就能解决这个内存暴涨的问题。知道原因的话可以交流。
