### ISSUE TITLE
内存暴涨解决方案

### ISSUE THREAD

**Issue by gdhGaoFei** [svga/SVGAPlayer-iOS#124]
if ([SVGAVideoEntity isMP3Data:protoImages[key]]) {
// mp3
[audiosData setObject:protoImages[key] forKey:key];
} else {
UIImage *image = [[UIImage alloc] initWithData:protoImages[key] scale:2.0];
if (image != nil) {
image = [image imageByResizeToSize:image.size];
[images setObject:image forKey:key];
}
}

(UIImage *)imageByResizeToSize:(CGSize)size {
if (size.width <= 0 || size.height <= 0) return nil;
UIGraphicsBeginImageContextWithOptions(size, NO, self.scale);
[self drawInRect:CGRectMake(0, 0, size.width, size.height)];
UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
UIGraphicsEndImageContext();
return image;
}
找到相应的位置，调用这个imageByResizeToSize方法就能解决这个内存暴涨的问题。但是原因不清楚，知道原因的话可以互相交流。

**Comment by PonyCui** [comment]
你把图片宽高各缩小了一半，那肯定没问题啦，问题就是模糊了咯。

**Comment by yangqingren** [comment]
hi，在 iOS 中，initWithData 生成图像是不会对其进行解码的，image 会在渲染的时候进行解码；
而 drawInRect 在绘制时，需先解码图片，再生成原始分辨率大小的 bitmap，这是很耗内存的；
这只是一个提前解码的操作而已
