### ISSUE TITLE
parseWithURL

### ISSUE THREAD

**Issue by lsj980Ya** [svga/SVGAPlayer-iOS#13]
下载完成的时候只缓存到了NSCache没有写入本地，导致app重启后每次都要下载

**Comment by PonyCui** [comment]
NSURLRequestUseProtocolCachePolicy
https://www.jianshu.com/p/f5064c77c5e9

**Comment by marshallee** [comment]
我说是本地缓存，不是请求的缓存策略
NSData *tag = [data subdataWithRange:NSMakeRange(0, 4)];
    if (![[tag description] isEqualToString:@"<504b0304>"]) {
        // Maybe is SVGA 2.0.0
        [parseQueue addOperationWithBlock:^{
            NSData *inflateData = [self zlibInflate:data];
            NSError *err;
            SVGAProtoMovieEntity *protoObject = [SVGAProtoMovieEntity parseFromData:inflateData error:&err];
            if (!err) {
                SVGAVideoEntity *videoItem = [[SVGAVideoEntity alloc] initWithProtoObject:protoObject cacheDir:@""];
                [videoItem resetImagesWithProtoObject:protoObject];
                [videoItem resetSpritesWithProtoObject:protoObject];
                [videoItem saveCache:cacheKey];
               **_# //这里不加上本地缓存？？？？，不加的话parseWithURL 的第一个本地判断不走，每次app重新启动NSCache中没有值，都再下载一遍，难道是我理解错了_**
                if (completionBlock) {
                    [[NSOperationQueue mainQueue] addOperationWithBlock:^{
                        completionBlock(videoItem);
                    }];
                }
            }
        }];
        return ;
    }

**Comment by lsj980Ya** [comment]
因为没有和服务器约定缓存，建议加上本地缓存

**Comment by PonyCui** [comment]
如果需要本地缓存，你可以自行使用 NSData 的方式处理。
