### ISSUE TITLE
近期有没有swift版本

### ISSUE THREAD

**Issue by zaishihuang** [svga/SVGAPlayer-iOS#132]
有无swift版本, svga2.x 依赖Protobuff. 项目使用的是swift版本，不希望再引入oc版本的protobuff

**Comment by zaishihuang** [comment]
写了个swift版本的SVGA播放器，有需要的可以使用。
https://github.com/zaishihuang/SwiftSvga

**Comment by PonyCui** [comment]
官方不会有 swift 支持版本
