### ISSUE TITLE
动画位置问题

### ISSUE THREAD

**Issue by DonsonWu** [svga/SVGAPlayer-iOS#133]
使用提供的demo，通过storyboard修改SVGAPlayer的frame后，动画置顶播放，不会居中播放，请问怎么让动画居中播放？
![Xnip2020-06-23_11-12-01](https://user-images.githubusercontent.com/15194024/85356781-61b5e100-b542-11ea-8308-ea0e8e436d8c.png)

**Comment by LChao05** [comment]
player.contentMode = UIViewContentModeCenter
试一下

**Comment by DonsonWu** [comment]
> player.contentMode = UIViewContentModeCenter
> 试一下

谢谢提醒，我试了。UIViewContentModeCenter，会变形。
使用 UIViewContentModeScaleAspectFit 可以。
