### ISSUE TITLE
iOS 不能播放SVGA动画里面的音乐怎么处理？谢谢

### ISSUE THREAD

**Issue by wangteng2021** [svga/SVGAPlayer-iOS#137]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by PonyCui** [comment]
请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by wangteng2021** [comment]
iOS播放svga动画的时候，动画自带的声音不能播放。Android就可以正常播放。我不确定是不是我的使用方法有问题。
下图是我使用的方法




                           王腾              
 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "svga/SVGAPlayer-iOS"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 下午4:18
收件人:&nbsp;"svga/SVGAPlayer-iOS"<SVGAPlayer-iOS@noreply.github.com&gt;;
抄送:&nbsp;"倔强的程序员"<954895928@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [svga/SVGAPlayer-iOS] iOS 不能播放SVGA动画里面的音乐怎么处理？谢谢 (#137)





 
请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）
