### ISSUE TITLE
iPhoneX以上屏幕刷新频率为120的机型上，svga动画缩短一半

### ISSUE THREAD

**Issue by qingmomo** [svga/SVGAPlayer-iOS#138]
中文：
请看一下svga内部startAnimation内部CADisplayLink，frameInterval计算时写死的60这个数值

English:
Take a look inside svga at startAnimation inside CADisplayLink frameInterval where 60 was written dead

**Comment by yangqingren** [comment]
iPhone 还未出现 120 刷新率的设备，以下为 iPad Pro 120 刷新率数据：

![IMG_00034](https://user-images.githubusercontent.com/15520051/94107746-ac603580-fe70-11ea-9b40-e7708f16ed09.PNG)

在 120 刷新率下，
设置 frameInterval 为 1 时，系统会自动将其置为 2（因为定时器并未开启 120 刷新率能力），
这使得其与 60 刷新率设备有一样的定时器表现，
所以在 120 刷新率下也是不会出现问题

**Comment by yangqingren** [comment]
如果要开启 120 刷新率，
需要在 info CADisableMinimumFrameDuration 设置为 YES，
并且 displayLink.preferredFramesPerSecond = 120，
现在 svga-iOS player 并没有这样做，所以定时器不会以 120 刷新率运行，
如有问题，我们可以接着讨论
