### ISSUE TITLE
I found a crash when the svga startAnimation

### ISSUE THREAD

**Issue by Mingmingmew** [svga/SVGAPlayer-iOS#14]
![image](https://user-images.githubusercontent.com/16685324/37581025-ac730b2a-2b81-11e8-8a36-c10bcce625dd.png)

**Comment by PonyCui** [comment]
issue 描述不清

**Comment by Mingmingmew** [comment]
就是崩溃崩在了你们得SDK里面

**Comment by PonyCui** [comment]
你提供的信息未足够让我们定位问题，请提供一个可重现的 Demo。
