### ISSUE TITLE
看了SDK的代码，是有沙盒存储相关的代码。实际是每次解析网络URL，都会去请求网络重新下载。为什么不把沙盒与内存缓存做好了？求回复。

### ISSUE THREAD

**Issue by Napoleon-D** [svga/SVGAPlayer-iOS#142]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-iOS#cache
大部分 Player 库都不会主动进行持久化处理

**Comment by changzengjing** [comment]
请尽量使用英文提交 Issue 这貌似是家中国公司吧

**Comment by gongdeyin** [comment]
@PonyCui 但是这个库，不是单纯的Player 库，Player库只是其中一个子库，包括 下载 解析 播放 三个大的组件，而缓存应该属于下载功能的子功能，应该做一个缓存。
