### ISSUE TITLE
iOS偶发蒙版失效

### ISSUE THREAD

**Issue by Wakever** [svga/SVGAPlayer-iOS#146]
当列表显示多个相同svga时，很容易出现蒙版失效的情况，导致显示异常

**Comment by Wakever** [comment]
[Uploading svga_test.zip…]()

**Comment by Wakever** [comment]
[svga_test.zip](https://github.com/svga/SVGAPlayer-iOS/files/5516316/svga_test.zip)

附上demo和录制视频，麻烦看看

**Comment by DonsonWu** [comment]
我也遇到了这个问题，是svga的问题还是代码问题，请问有什么解决方案没有?

**Comment by DonsonWu** [comment]
> [svga_test.zip](https://github.com/svga/SVGAPlayer-iOS/files/5516316/svga_test.zip)
> 
> 附上demo和录制视频，麻烦看看

我也遇到了这个问题，是svga的问题还是代码问题，请问有什么解决方案没有?

**Comment by Batxent** [comment]
同样出现了该问题

**Comment by superQiang** [comment]
有解决方案了吗？遇到类似问题，新的设计出的扫光动画，偶发低端机不显示

**Comment by BingMax** [comment]
有解决方案了吗? 我的也遇到列表中有多个时, 蒙版失效

**Comment by UncleJoker** [comment]
同一时间在不同界面播放同一个SVGA动画，会出现蒙版异常显示问题，请问这个有解决方案吗？

**Comment by wymobob** [comment]
同问，能不能来个人解决一下

**Comment by yangqingren** [comment]
你好，这个是 cell 的复用问题，跟 svga 无关哦

**Comment by yangqingren** [comment]
你好，这边可以这样子解决，自己管理 videoItem，而不需要在 cell 复用的时候去动态解析

**Comment by PonyCui** [comment]
可能是因为 mask 中的 CAShapeLayer 被复用的原因导致的。

**Comment by FITZ-ZHANG-GITHUB** [comment]
> 同一时间在不同界面播放同一个SVGA动画，会出现蒙版异常显示问题，请问这个有解决方案吗？

也遇到了同样的问题

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-iOS/commit/5df66ba53d88c1f6d2b42b85aa83fdca621918d7
Fiexed at 2.5.7
