### ISSUE TITLE
iPhoneX以上屏幕svga动画不居中偏上且不能全屏显示

### ISSUE THREAD

**Issue by xprocwin7** [svga/SVGAPlayer-iOS#148]
svga的大小是整个屏幕的大小，iPhoneX以上屏幕svga动画不居中偏上，且不能全屏显示，iPhoneX以下可以全屏显示，也能居中
不管在那个手机上，_videoSize的高度永远是1334

**Comment by xprocwin7** [comment]
![image](https://user-images.githubusercontent.com/16574630/99508321-6bdbee80-29bf-11eb-866e-de3ac270aacf.png)

**Comment by yangqingren** [comment]
你好，根据描述无法定位具体问题，尝试使用 player.contentMode，或者提供更多信息

**Comment by TZXZ** [comment]
[self setContentMode:UIViewContentModeScaleAspectFit]; ?
