### ISSUE TITLE
Non-public API usage from SSZipArchive

### ISSUE THREAD

**Issue by IvanChan** [svga/SVGAPlayer-iOS#150]
ITMS-90338: Non-public API usage - The app references non-public selectors : zipArchiveDidUnzipFileAtIndex:totalFiles:archivePath:unzippedFilePath:, zipArchiveProgressEvent:total:.

**Comment by xchenLee** [comment]
i have the same problem, have you resolved this?

**Comment by PonyCui** [comment]
@xchenLee https://github.com/ZipArchive/ZipArchive/issues/513
