### ISSUE TITLE
显示不全，背景图片丢失，但是同一个文件安卓与svga-preview上可以正常显示

### ISSUE THREAD

**Issue by hamburger9527** [svga/SVGAPlayer-iOS#151]
如图：
![image](https://user-images.githubusercontent.com/15826415/102734664-5588d000-437b-11eb-8388-2e2e42d68177.png)
![image](https://user-images.githubusercontent.com/15826415/102734678-5d487480-437b-11eb-8c89-877666eae30b.png)
附上文件：

[test.svga.zip](https://github.com/svga/SVGAPlayer-iOS/files/5722081/test.svga.zip)

**Comment by PonyCui** [comment]
iOS 暂时不支持 jpg 作为素材，你可以联系工程师稍作改动代码，也可以使用 png 作为背景素材。
