### ISSUE TITLE
我在线上环境中发现了一个崩溃，崩溃在你们的parseWithURL->cacheKey->MD5String方法里面

### ISSUE THREAD

**Issue by Mingmingmew** [svga/SVGAPlayer-iOS#16]
![image](https://user-images.githubusercontent.com/16685324/37808907-deacd36a-2e87-11e8-8281-e1e0f9f0d185.png)
![image](https://user-images.githubusercontent.com/16685324/37808918-ef37ead0-2e87-11e8-9c02-4734fbb7cc92.png)
![image](https://user-images.githubusercontent.com/16685324/37808999-4ab0fc26-2e88-11e8-83c5-1614e2d31b7e.png)
这样子的信息可以定位了没？

**Comment by Mingmingmew** [comment]
具体URL我这边也不太清楚 但是这个里面能不能先让它不崩 抛错误也行

**Comment by PonyCui** [comment]
没有具体的 Demo 是无法定位问题的

**Comment by Mingmingmew** [comment]
那我们先想办法重现

**Comment by PonyCui** [comment]
最常见的问题是，你在 parseWithURL 中传入了一个错误的对象。
