### ISSUE TITLE
startAnimationWithRange 方法无效

### ISSUE THREAD

**Issue by linyezz** [svga/SVGAPlayer-iOS#160]
使用版本：2.5.6
函数中的range参数失效原因是drawLayer变量为nil的时候重新给videoItem变量赋值，走了SET方法，currentRange变成初始化数据

**Comment by yangqingren** [comment]
currentRange 在 SET 初始化之后，还会继续赋值，包括 currentRange 和 currentFrame，本地验证无问题哦  in tag 2.5.6
