### ISSUE TITLE
ios矢量路径的描边动画会在拐角处裂开

### ISSUE THREAD

**Issue by EggKim** [svga/SVGAPlayer-iOS#162]
[落地视频和ae工程.zip](https://github.com/svga/SVGAPlayer-iOS/files/6767064/ae.zip)

**Comment by PonyCui** [comment]
https://github.com/svga/SVGAPlayer-iOS/commit/a340940236846f0c36ae08244ddfbd67553048cd
Fixed at 2.5.7
