### ISSUE TITLE
项目中集成了SVGA，解压zip时失败

### ISSUE THREAD

**Issue by Dombo-Y** [svga/SVGAPlayer-iOS#17]
Error Domain=SSZipArchiveErrorDomain Code=-1 "failed to open zip file" UserInfo={NSLocalizedDescription=failed to open zip file}
怎么解决。。。pod集成的，不清楚问题原因。。用的是demo的参数，demo是好的

**Comment by Virtue86** [comment]
SSZipArchive 需要1.8版本的。之前是这样

**Comment by Dombo-Y** [comment]
找到问题了，确实是SSZipArchive版本的问题，项目中之前用的是1.4的。。。感谢

**Comment by PonyCui** [comment]
@Virtue86 感谢你的解答
