### ISSUE TITLE
SVGA文件在Andorid端播放正常，但是IOS播放只显示一部分动画

### ISSUE THREAD

**Issue by czy-commit-bug** [svga/SVGAPlayer-iOS#177]
Related code：

addSubview(self.voiceWaveView)
        
        let parser = SVGAParser.init()
//        room_reppId
        parser.parse(withNamed: "room_water", in: nil) { [weak self] (videoItem) in
            guard let `self` = self else { return }

                self.voiceWaveView.videoItem = videoItem
                self.voiceWaveView.startAnimation()

        }

[self.SonicParser parseWithURL:[NSURL URLWithString:svga] completionBlock:^(SVGAVideoEntity * _Nullable videoItem) {
                if (videoItem != nil) {
                    self.SonicPlayer.videoItem = videoItem;
                    [self.SonicPlayer startAnimation];
                }
            }  #failureBlock:nil];

**Comment by 846825177** [comment]
file link：[https://qumi-1304843926.cos.ap-shanghai.myqcloud.com/ios_res/%E5%90%88%E6%88%90%201.svga](url)

**Comment by PonyCui** [comment]
录个视频看看？

**Comment by czy-commit-bug** [comment]
好的，稍等

**Comment by 846825177** [comment]
https://qumi-1304843926.cos.ap-shanghai.myqcloud.com/ios_res/normal%20video.mp4

**Comment by czy-commit-bug** [comment]
我们把版本更新至最新，问题已解决
