### ISSUE TITLE
About cache invalidation

### ISSUE THREAD

**Issue by JasonStu** [svga/SVGAPlayer-iOS#23]
你好！我这边服务端按照你文档所说的提供相关的 Cache-Control  但是发现还是没走内存，请问是跟svga的大小有关系吗? 我的这个svga 是3M左右

 { URL: https://********6bbe7b8c2695517de5dccd2f9764415a.svga } { Status Code: 200, Headers 	{
	Last-Modified = 	(
		"Tue, 20 Mar 2018 06:18:58 GMT",
	),
	access-control-allow-methods = 	(
		"GET, POST",
	),
	Server = 	(
		"Tengine",
	),
	timing-allow-origin = 	(
		"*",
	),
	Cache-Control = 	(
		"max-age=604800",
	),
	x-oss-request-id = 	(
		"5AD9BBD8663518FF6D6F0541",
	),
	Accept-Ranges = 	(
		"bytes",
	),
	x-oss-hash-crc64ecma = 	(
		"2346656011198604988",
	),
	Access-Control-Allow-Origin = 	(
		"*",
	),
	Content-Length = 	(
		"3569299",
	),
	x-swift-savetime = 	(
		"Fri, 20 Apr 2018 10:07:20 GMT",
	),
	Via = 	(
		"cache2.l2st3-2[77,304-0,H], cache22.l2st3-2[80,0], kunlun9.cn116[0,200-0,H], kunlun10.cn116[1,0]",
	),
	content-md5 = 	(
		"HafrWi2tn81myrYlwrXpOw==",
	),
	Date = 	(
		"Fri, 20 Apr 2018 10:07:20 GMT",
	),
	x-oss-server-time = 	(
		"14",
	),
	eagleid = 	(
		"7793970a15242211477701005e",
	),
	Age = 	(
		"2307",
	),
	x-oss-o

**Comment by PonyCui** [comment]
Maybe
这么大的 svga 文件是不正常的，请扔回去让设计师重新设计。

**Comment by JasonStu** [comment]
@PonyCui 请问我的设计请求头配置是正常么

**Comment by PonyCui** [comment]
正确的

**Comment by zhhwdev** [comment]
这边能给一个iOS平台在稍微复杂的动画的CPU大致占用吗？比如你们那个天使的；我想看下和帧动画的CPU及内存的区别

**Comment by PonyCui** [comment]
在 2.1.3 版本中，已默认使用缓存，不再从服务器重复下载。
