### ISSUE TITLE
Memory increase very fast when i play a svga file 

### ISSUE THREAD

**Issue by ws4715535** [svga/SVGAPlayer-iOS#24]
Memory increase very fast when i play a SVGA file 
1.  Our SVGA file is about 4m. When i play one animate and stop , but the memory increase very fast and can't reduce to a normal level

2. Did this player has some limit to SVGA source , or did our SVGA files is too big???

thx

**Comment by PonyCui** [comment]
ask your designer, optimize SVGA file. Our animation converter will alert designer, do not export file while over memory-limit.
