### ISSUE TITLE
依赖的protobuf库，在打包的时候头文件引入不了，报错

### ISSUE THREAD

**Issue by xiaowoniu2012** [svga/SVGAPlayer-iOS#25]
xcode9 xcodebuild打包时，报错：fatal error: 'google/protobuf/Any.pbobjc.h' file not found
版本:
Installing Protobuf (3.5.0)

**Comment by PonyCui** [comment]
请提供一个可复现的 Demo

**Comment by JimmyGoGoGo** [comment]
同样，用在module里面的话会报这个错，好像是宏定义没生效。请问解决了吗？
