### ISSUE TITLE
依赖SSZipArchive的问题

### ISSUE THREAD

**Issue by badoychen** [svga/SVGAPlayer-iOS#26]
podspec里指定了SSZipArchive库，1.8.1目前编译会和openssl存在链接冲突的情况  最新版的SSZipArchive应该解决了，依赖项不要写死1.8.1

**Comment by PonyCui** [comment]
2.x SSZipArchive 会在某些情况下 crash

**Comment by PonyCui** [comment]
目前，没有看到官方有任何修复。

**Comment by PonyCui** [comment]
Fixed. You can use 2.3.1 version.
https://github.com/yyued/SVGAPlayer-iOS/commit/116a91fd94a76caf042126a216bc8bd3012dae06

**Comment by zhangfushuai** [comment]
How to use 2.3.1 version with cocoapods
