### ISSUE TITLE
关于内存暴增的问题

### ISSUE THREAD

**Issue by tulermos** [svga/SVGAPlayer-iOS#31]
一加载动画，内存就会暴增。我们已经在动画结束的回调方法里面添加了remove的方法
-(void)svgaPlayerDidFinishedAnimation:(SVGAPlayer *)player
{
    [_aPlayer stopAnimation];
    [_aPlayer clear];

}
请问还有什么可以优化内存的方法吗？

**Comment by PonyCui** [comment]
先优化 SVGA 文件，这个优化需要由设计师完成。

**Comment by errnull** [comment]
已回复邮件，麻烦提供一下使用的 SVGA 文件到 help@svga.io
