### ISSUE TITLE
我们使用AE导出了svga，但是IOS端却播放不了，一直是黑屏

### ISSUE THREAD

**Issue by wzhs** [svga/SVGAPlayer-iOS#32]
我们使用AE导出了svga，但是IOS端却播放不了，一直是黑屏。但是在web端播放正常。如果要应用的IOS端是否需要做特殊的设置，或者在做动画的时候需要注意什么？

**Comment by wzhs** [comment]
补充：SVGAPLayer 没有报错

**Comment by PonyCui** [comment]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：**问题的描述、重现方式、附件（提供一个 Demo 以重现问题）**

**Comment by wzhs** [comment]
好的，目前我们测试了使用URL的方式加载，这个可以播放。但是本地加载则不可以。但是你们提供的例子，本地加载能播放。
SVGA文件：http://manage.shunxiangtech.com/vga/meigui2.0.svga

**Comment by PonyCui** [comment]
这个问题，你需要自己查找一下原因哦。

**Comment by wzhs** [comment]
我看到Demo都是以URL形式加载的，那么本地加载的流程是什么？

**Comment by wzhs** [comment]
有没有SVGA本地加载的Demo？？？

**Comment by PonyCui** [comment]
- (void)parseWithData:(nonnull NSData *)data
             cacheKey:(nonnull NSString *)cacheKey
      completionBlock:(void ( ^ _Nullable)(SVGAVideoEntity * _Nonnull videoItem))completionBlock
         failureBlock:(void ( ^ _Nullable)(NSError * _Nonnull error))failureBlock;

- (void)parseWithNamed:(nonnull NSString *)named
              inBundle:(nullable NSBundle *)inBundle
       completionBlock:(void ( ^ _Nullable)(SVGAVideoEntity * _Nonnull videoItem))completionBlock
          failureBlock:(void ( ^ _Nullable)(NSError * _Nonnull error))failureBlock;

**Comment by lzcdgit** [comment]
SVGA本地加载 是用这个吧？
(void)parseWithData:(nonnull NSData *)data
cacheKey:(nonnull NSString *)cacheKey
cachekey 是什么啊
