### ISSUE TITLE
 SVGABezierPath crash

### ISSUE THREAD

**Issue by dijiufun** [svga/SVGAPlayer-iOS#33]
[EXC_CRASH(SIGABRT).txt](https://github.com/yyued/SVGAPlayer-iOS/files/2301311/EXC_CRASH.SIGABRT.txt)

创建一个页面加载两个本地的svga文件，push这个viewController，然后显示动画（动画循环）pop这个viewController
不停的重复上面的操作，偶尔会出现crash

"os_version":"iPhone OS 10.0.1 (14A403)"

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Application Specific Information:
abort() called

Filtered syslog:
None found

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x0000000180642014 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x0000000180709460 pthread_kill + 112
2   libsystem_c.dylib             	0x00000001805b63f4 abort + 140
3   libsystem_malloc.dylib        	0x0000000180686a38 _nano_vet_and_size_of_live + 0
4   libsystem_malloc.dylib        	0x0000000180687db8 nano_free + 220
5   CoreFoundation                	0x0000000181623e8c _CFRelease + 1264
6   CoreFoundation                	0x00000001816339fc _CFStringCreateWithFormatAndArgumentsAux2 + 268
7   Foundation                    	0x0000000182052218 +[NSString stringWithFormat:] + 68
8   XXXXXX-ios                   	0x00000001012c9168 BLYThreadBacktraceSymbolicate + 520
9   XXXXXX-ios                   	0x00000001012c8398 BLYCrashHandlerCallback + 2860
10  XXXXXX-ios                   	0x00000001012c55bc BLYBSDSignalHandlerCallback + 92
11  libsystem_platform.dylib      	0x0000000180703348 _sigtramp + 52
12  libsystem_pthread.dylib       	0x0000000180709460 pthread_kill + 112
13  libsystem_c.dylib             	0x00000001805b63f4 abort + 140
14  libsystem_malloc.dylib        	0x0000000180686a38 _nano_vet_and_size_of_live + 0
15  libsystem_malloc.dylib        	0x0000000180687db8 nano_free + 220
16  CoreFoundation                	0x0000000181623e8c _CFRelease + 1264
17  CoreFoundation                	0x00000001816339fc _CFStringCreateWithFormatAndArgumentsAux2 + 268
18  CoreFoundation                	0x0000000181657b98 _CFLogvEx2Predicate + 156
19  CoreFoundation                	0x0000000181657eec _CFLogvEx3 + 408
20  Foundation                    	0x000000018213b4e4 _NSLogv + 132
21  Foundation                    	0x00000001820623ec NSLog + 32
22  XXXXXX-ios                   	0x00000001012c5590 BLYBSDSignalHandlerCallback + 48
23  libsystem_platform.dylib      	0x0000000180703348 _sigtramp + 52
24  libsystem_pthread.dylib       	0x0000000180709460 pthread_kill + 112
25  libsystem_c.dylib             	0x00000001805b63f4 abort + 140
26  libsystem_malloc.dylib        	0x0000000180686a38 _nano_vet_and_size_of_live + 0
27  libsystem_malloc.dylib        	0x0000000180687db8 nano_free + 220
28  CoreFoundation                	0x0000000181623e8c _CFRelease + 1264
29  CoreFoundation                	0x00000001816339fc _CFStringCreateWithFormatAndArgumentsAux2 + 268
30  CoreFoundation                	0x0000000181657b98 _CFLogvEx2Predicate + 156
31  CoreFoundation                	0x0000000181657eec _CFLogvEx3 + 408
32  Foundation                    	0x000000018213b4e4 _NSLogv + 132
33  Foundation                    	0x00000001820623ec NSLog + 32
34  XXXXXX-ios                   	0x00000001012c5590 BLYBSDSignalHandlerCallback + 48
35  libsystem_platform.dylib      	0x0000000180703348 _sigtramp + 52
36  libsystem_pthread.dylib       	0x0000000180709460 pthread_kill + 112
37  libsystem_c.dylib             	0x00000001805b63f4 abort + 140
38  libsystem_malloc.dylib        	0x0000000180686a38 _nano_vet_and_size_of_live + 0
39  libsystem_malloc.dylib        	0x0000000180687db8 nano_free + 220
40  CoreFoundation                	0x0000000181623e8c _CFRelease + 1264
41  CoreFoundation                	0x00000001816339fc _CFStringCreateWithFormatAndArgumentsAux2 + 268
42  CoreFoundation                	0x0000000181657b98 _CFLogvEx2Predicate + 156
43  CoreFoundation                	0x0000000181657eec _CFLogvEx3 + 408
44  Foundation                    	0x000000018213b4e4 _NSLogv + 132
45  Foundation                    	0x00000001820623ec NSLog + 32
46  XXXXXX-ios                   	0x00000001012c5590 BLYBSDSignalHandlerCallback + 48
47  libsystem_platform.dylib      	0x0000000180703348 _sigtramp + 52
48  libsystem_pthread.dylib       	0x0000000180709460 pthread_kill + 112
49  libsystem_c.dylib             	0x00000001805b63f4 abort + 140
50  libsystem_malloc.dylib        	0x0000000180686a38 _nano_vet_and_size_of_live + 0
51  libsystem_malloc.dylib        	0x0000000180687db8 nano_free + 220
52  CoreFoundation                	0x0000000181623e8c _CFRelease + 1264
53  CoreFoundation                	0x00000001816339fc _CFStringCreateWithFormatAndArgumentsAux2 + 268
54  CoreFoundation                	0x0000000181657b98 _CFLogvEx2Predicate + 156
55  CoreFoundation                	0x0000000181657eec _CFLogvEx3 + 408
56  Foundation                    	0x000000018213b4e4 _NSLogv + 132
57  Foundation                    	0x00000001820623ec NSLog + 32
58  XXXXXX-ios                   	0x00000001012c5590 BLYBSDSignalHandlerCallback + 48
59  libsystem_platform.dylib      	0x0000000180703348 _sigtramp + 52
60  libsystem_pthread.dylib       	0x0000000180709460 pthread_kill + 112
61  libsystem_c.dylib             	0x00000001805b63f4 abort + 140
62  libsystem_malloc.dylib        	0x0000000180686a38 _nano_vet_and_size_of_live + 0
63  libsystem_malloc.dylib        	0x0000000180687db8 nano_free + 220
64  CoreFoundation                	0x000000018163e5d0 __CFStringChangeSizeMultiple + 2716
65  CoreFoundation                	0x000000018163be3c __CFStringCheckAndReplace + 736
66  CoreFoundation                	0x000000018157b418 -[__NSCFString appendString:] + 52
67  Foundation                    	0x00000001820ca93c -[NSRegularExpression(NSReplacement) stringByReplacingMatchesInString:options:range:withTemplate:] + 512
68  Foundation                    	0x00000001820ca6e4 -[NSString(NSRegularExpressionSupport) _stringByReplacingOccurrencesOfRegularExpressionPattern:withTemplate:options:range:] + 276
69  XXXXXX-ios                   	0x000000010271074c -[SVGABezierPath setValues:] + 164
70  XXXXXX-ios                   	0x0000000102710c18 -[SVGABezierPath createLayer] + 100
71  XXXXXX-ios                   	0x000000010271a8a8 -[SVGAVectorLayer createCurveLayerWithProto:] + 404
72  XXXXXX-ios                   	0x000000010271a42c -[SVGAVectorLayer drawFrame:] + 1200
73  XXXXXX-ios                   	0x0000000102711bfc -[SVGAContentLayer stepToFrame:] + 728
74  XXXXXX-ios                   	0x00000001027182e4 -[SVGAPlayer update] + 344
75  XXXXXX-ios                   	0x0000000102718588 -[SVGAPlayer next] + 544
76  QuartzCore                    	0x0000000184877640 CA::Display::DisplayLinkItem::dispatch(unsigned long long) + 44
77  QuartzCore                    	0x00000001848774ec CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 444
78  IOKit                         	0x00000001818e0570 IODispatchCalloutFromCFMessage + 372
79  CoreFoundation                	0x000000018160a56c __CFMachPortPerform + 180
80  CoreFoundation                	0x0000000181622934 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
81  CoreFoundation                	0x00000001816220e8 __CFRunLoopDoSource1 + 436
82  CoreFoundation                	0x000000018161fbcc __CFRunLoopRun + 1840
83  CoreFoundation                	0x000000018154e048 CFRunLoopRunSpecific + 444
84  GraphicsServices              	0x0000000182fd1198 GSEventRunModal + 180
85  UIKit                         	0x0000000187527818 -[UIApplication _run] + 684
86  UIKit                         	0x0000000187522550 UIApplicationMain + 208
87  XXXXXX-ios                   	0x00000001007f0e14 main (main.m:23)
88  libdyld.dylib                 	0x00000001805305b8 start + 4

**Comment by PonyCui** [comment]
Thank you for your feedback, we will try to fix it.

**Comment by errnull** [comment]
[SVGA-Playground](https://github.com/errnull/SVGA-Playground)
随手做的这个 demo，
在 iPhone 6 iOS 10.3 似乎没办法复现这个问题。
@dijiufun

**Comment by errnull** [comment]
responding timeout.
please reopen the issue and provide more info.
