### ISSUE TITLE
自定义AttributeText超出key对应的文本框大小

### ISSUE THREAD

**Issue by stackJolin** [svga/SVGAPlayer-iOS#34]
## Issue Template
自定义Attribute超出key对应的文本框大小

**Comment by PonyCui** [comment]
暂时没有特别的解决方案，需要你自己确定字符是否超出边界，并加以裁剪。

**Comment by stackJolin** [comment]
![image](https://user-images.githubusercontent.com/14361098/44441295-764f8800-a5fe-11e8-8d6c-7d0e1ba7144e.png)
我这样去取某一帧对应的Frame，可以吗

**Comment by PonyCui** [comment]
你可以尝试获取第一帧的某元素大小
