### ISSUE TITLE
获取svga格式文件为nil

### ISSUE THREAD

**Issue by wqforever** [svga/SVGAPlayer-iOS#35]
[[NSBundle mainBundle]pathForResource:@“test” ofType:@"svga"]

这个获取的路径为空，是识别不了svga格式的文件吗？

**Comment by wqforever** [comment]
是我的文件格式导出错误吗？

**Comment by wqforever** [comment]
再次补充下，我的svga放在你们网站能预览成功，但是在工程里获取失败，应该是识别不了。
然后用你们demo里的rose_1.5.0可以，rose_2.0.0又不行了

**Comment by PonyCui** [comment]
1. > pod setup
2. > pod install

**Comment by wqforever** [comment]
Using Protobuf (3.5.0)
Using SSZipArchive (1.8.1)
Using SVGAPlayer (2.1.2)
这是我用的版本，应该是最新的

**Comment by PonyCui** [comment]
请提供一个可复现问题的 Demo，如需获得更实时的问答建议到知乎付费咨询。https://www.zhihu.com/zhi/people/1011556735563157504
