### ISSUE TITLE
如何释放内存

### ISSUE THREAD

**Issue by Dombo-Y** [svga/SVGAPlayer-iOS#36]
加载很大的SVGA文件后（10M左右的），会发现内容暴增的情况（100-300M不等），并且无法释放，有没有好的解决办法
放在Demo中也是同样的内存暴增情况，目前多播放了几个Svga文件就导致内存崩了，如何解决。谢谢

**Comment by PonyCui** [comment]
本身 SVGA 文件这么大就是不正常的，请优化文件，如果需要协助优化文件，你可以通过付费咨询进行，https://www.zhihu.com/zhi/people/1011556735563157504 。

**Comment by pengxu1013** [comment]
内存暴涨,并且无法释放,怎么破?
