### ISSUE TITLE
SVGA内存不释放的原因及解决

### ISSUE THREAD

**Issue by changjianfeishui** [svga/SVGAPlayer-iOS#38]
SVGAPlayer-iOS使用了NSCache管理缓存. 

在`SVGAVideoEntity`类的`saveCache:`方法中,

```
- (void)saveCache:(NSString *)cacheKey {
    [videoCache setObject:self forKey:cacheKey];
}
```

将`self`作为key会导致static类型的全局变量videoCache对其进行强引用, 需要立即进行内存释放的可以修改其缓存逻辑.  否则, NSCache将会在系统内存警告时才会自动释放部分缓存.

**Comment by PonyCui** [comment]
这并没有什么问题，内存不警告，多占点内存也没关系。

**Comment by sqzxcv** [comment]
> 这并没有什么问题，内存不警告，多占点内存也没关系。

这个人是 SB，想钱想疯了把
