### ISSUE TITLE
Crash ,- (BOOL)isKeepFrame:(SVGAVideoSpriteFrameEntity *)frameItem

### ISSUE THREAD

**Issue by allen8517** [svga/SVGAPlayer-iOS#39]
- (BOOL)isKeepFrame:(SVGAVideoSpriteFrameEntity *)frameItem {
    if ([frameItem.shapes.firstObject isKindOfClass:[NSDictionary class]]) {
        return [frameItem.shapes.firstObject[@"type"] isKindOfClass:[NSString class]] &&
        [frameItem.shapes.firstObject[@"type"] isEqualToString:@"keep"];
    }
    else if ([frameItem.shapes.firstObject isKindOfClass:[SVGAProtoShapeEntity class]]) {
        return [(SVGAProtoShapeEntity *)frameItem.shapes.firstObject type] == SVGAProtoShapeEntity_ShapeType_Keep;
    }
    else {
        return NO;
    }
}

//建议加上判断
if !frameItem.shapes.count {
      return NO;
}

**Comment by PonyCui** [comment]
Please provide a demo, firstObject call will not leads crash.
