### ISSUE TITLE
我们美术导出来的svga资源在iOS上不能解压

### ISSUE THREAD

**Issue by GasparChu** [svga/SVGAPlayer-iOS#4]
我们美术导出来的.svga资源在iOS上不能解压，报错failed to open zip file；但是在安卓上可以解压出来，请问是什么问题？

**Comment by PonyCui** [comment]
```
pod 'SVGAPlayer', '2.0.1'
```

如果不成功， ```pod setup```，原因是，你本地的 pod 仓库太旧。

**Comment by GasparChu** [comment]
好了，是sszip版本也低了，谢谢
