### ISSUE TITLE
内存释放

### ISSUE THREAD

**Issue by hebing789** [svga/SVGAPlayer-iOS#40]
创建一个页面加载两个本地的svga文件，在viewWillAppear里面显示动画,在viewWillDisappear里面消失动画,调用以下代码
     [self.aPlayer stopAnimation];
        [self.aPlayer clear];
     [self.aPlayer clearDynamicObjects];
    if (self.aPlayer.superview != nil) {
        [self.aPlayer removeFromSuperview];
    }
        self.aPlayer = nil;
push这个viewController，然后显示动画（动画循环）pop这个viewController
不停的重复上面的操作，会出现内存增加

**Comment by PonyCui** [comment]
我会尝试一下看看能不能重现问题

**Comment by xiaohuihui000** [comment]
这个问题我也发现了 解决了吗

**Comment by xiaohuihui000** [comment]
2.3.1版本有时候会闪退，

@PonyCui 
<img width="1351" alt="2018-12-24 4 15 43" src="https://user-images.githubusercontent.com/24727182/50394294-8edfd280-0797-11e9-8795-5018a12d4ed9.png">

**Comment by PonyCui** [comment]
应该是 SSZipArchiver 导致的闪退，官方仍然没有修复这个问题。

**Comment by PonyCui** [comment]
建议你使用 svga 2.0 格式文件， 2.0 格式文件不用依赖 Zip。

**Comment by rocing** [comment]
这个问题解决了吗

**Comment by PonyCui** [comment]
可以通过指定 SSZipArchive 版本为 1.8.1 解决问题
也可以不使用 1.0 格式的 svga 文件避免问题

**Comment by pengxu1013** [comment]
播放svga内存会逐渐上涨且不往下降,如何释放?

**Comment by errnull** [comment]
[SVGA-Playground](https://github.com/errnull/SVGA-Playground/tree/memory-dev)
随手做的这个 demo，
在 iPhone 6 iOS 10.3 似乎没办法复现这个问题。
@pengxu1013 @hebing789

**Comment by errnull** [comment]
responding timeout.
please reopen the issue and provide more info.

**Comment by pengxu1013** [comment]
你自己demo就能复现啊 说的是内存 涨上去之后礼物播放完毕不降 加载url礼物的话更明显 @xiaohuihui000

**Comment by errnull** [comment]
相关问题可以关注一下 issue 85 #85 
@pengxu1013

**Comment by errnull** [comment]
![屏幕快照2019-09-06下午6 18 57](https://user-images.githubusercontent.com/28481578/64420869-d2366300-d0d2-11e9-9215-9aed6801a9bd.png)
退出控制器内存会降到播放前。
@pengxu1013

**Comment by pengxu1013** [comment]
说的就是不退出的时候啊......🤦‍♂️

**Comment by pengxu1013** [comment]
说的就是不退出的时候啊......🤦‍♂️ @xiaohuihui000
