### ISSUE TITLE
videoCache私有没法手动释放

### ISSUE THREAD

**Issue by winddpan** [svga/SVGAPlayer-iOS#42]
static NSCache *videoCache;

这个私有 Cache 没法手动释放，加载多了内存占用只增没法降。

**Comment by PonyCui** [comment]
在内存不足时，占用的内存会被自动释放。

**Comment by PonyCui** [comment]
Fixed. You can use 2.3.1 version.
https://github.com/yyued/SVGAPlayer-iOS/commit/116a91fd94a76caf042126a216bc8bd3012dae06
