### ISSUE TITLE
videoCache 会引起内存暴增，播放六七个动画 iphone6  iphone6 Plus会闪退

### ISSUE THREAD

**Issue by chenqing512** [svga/SVGAPlayer-iOS#43]
videoCache 播放多个动画，IG的手机偶尔会闪退，内存溢出
注释掉[videoCache setObject:self forKey:cacheKey]; 就好了（不知道会不会产生其他问题）
videoCache 是做什么用的

**Comment by chenqing512** [comment]
videoCache 播放多个动画，IG的手机偶尔会闪退，内存溢出
注释掉[videoCache setObject:self forKey:cacheKey]; 就好了（不知道会不会产生其他问题）
videoCache 是做什么用的

**Comment by PonyCui** [comment]
NSCache use to reuse videoItem, but many issue relate to this, so we are considering remove this feature.

**Comment by PonyCui** [comment]
Fixed. You can use 2.3.1 version.
https://github.com/yyued/SVGAPlayer-iOS/commit/116a91fd94a76caf042126a216bc8bd3012dae06
