### ISSUE TITLE
SVGAParser里一段hardcode 是什么意思

### ISSUE THREAD

**Issue by Hero2000** [svga/SVGAPlayer-iOS#45]

**Comment by Hero2000** [comment]
if (![[tag description] isEqualToString:@"<504b0304>"])   
 SVGAParser.m 里有一个这个判断 麻烦问一下   这个hardcode 什么意思呢？  不有不走的情况吗

**Comment by PonyCui** [comment]
这是为了区分 svga 文件 1.0 和 2.0 版本的设定

**Comment by Hero2000** [comment]
那麻烦问一下是不是2.0 版本以后的svga文件 都会走到 if 判断里？

**Comment by PonyCui** [comment]
是
