### ISSUE TITLE
显示错误

### ISSUE THREAD

**Issue by jiangmingz** [svga/SVGAPlayer-iOS#47]
CGFloat ratio = self.bounds.size.height / self.videoItem.videoSize.height;
            CGPoint offset = CGPointMake(
                                         (1.0 - ratio) / 2.0 * self.videoItem.videoSize.width - (self.bounds.size.width - self.videoItem.videoSize.width * ratio) / 2.0,
                                         (1.0 - ratio) / 2.0 * self.videoItem.videoSize.height);
            self.drawLayer.transform = CATransform3DMakeAffineTransform(CGAffineTransformMake(ratio, 0, 0, ratio, -offset.x, -offset.y));
这里会超出父view的尺寸左边缘

**Comment by PonyCui** [comment]
Provide more information please, and use the issue template post again.
