### ISSUE TITLE
播放动画时，有其他界面交互（如连击），动画会卡顿

### ISSUE THREAD

**Issue by LMgod** [svga/SVGAPlayer-iOS#54]
加载较大的动画时，连击动画卡顿

[parser lv_parseWithURL:[NSURL URLWithString:NSNULLText(self.animateUrl)] completionBlock:^(SVGAVideoEntity * _Nullable videoItem) {
            if (videoItem != nil) {
                self.playerSVG.videoItem = videoItem;
                [self.playerSVG startAnimation];
                self.playerSVG.loops = 1;
            }else {
                [self removeFromSuperview];
                if (nil != self.callBack && [self.callBack respondsToSelector:@selector(biggestGiftViewFinishShowed:)]) {
                    [self.callBack biggestGiftViewFinishShowed:self];
                }
            }
        } failureBlock:^(NSError * _Nullable error) {
            [self removeFromSuperview];
            if (nil != self.callBack && [self.callBack respondsToSelector:@selector(biggestGiftViewFinishShowed:)]) {
                [self.callBack biggestGiftViewFinishShowed:self];
            }
        }]

**Comment by errnull** [comment]
你好，可以把 Demo 链接给一下吗。
还有测试设备参数。
@LMgod

**Comment by errnull** [comment]
responding timeout.
please reopen the issue and provide more info.
