### ISSUE TITLE
Trim path is in a wrong way

### ISSUE THREAD

**Issue by dong108** [svga/SVGAPlayer-iOS#55]
在用路径做trim动画的时候，展示出来的路径动画都错误无序了，详情在附件。

[map simp480_svga.svga.zip](https://github.com/yyued/SVGAPlayer-iOS/files/2977441/map.simp480_svga.svga.zip)

**Comment by PonyCui** [comment]
trim 路径动画确实存在问题

**Comment by dong108** [comment]
嗯  那就看大牛计划吧，你的项目真的很好啊~

**Comment by PonyCui** [comment]
我们正在重构 AE 的转换器了

**Comment by errnull** [comment]
https://github.com/svga/SVGA-AEConverter/raw/2.3.1/build/1.1.0/SVGAConverter_AE.zxp

**Comment by errnull** [comment]
> 嗯 那就看大牛计划吧，你的项目真的很好啊~

https://github.com/svga/SVGA-AEConverter/raw/2.3.1/build/1.1.0/SVGAConverter_AE.zxp
我们在 2.3.1 中完善了大多数的矢量导出，
可以使用这个新的插件包尝试。

# 暂不支持
* 路径外批量修剪
* offset 参数

**Comment by errnull** [comment]
@dong108

**Comment by errnull** [comment]
Have to fixed.
