### ISSUE TITLE
- (void)setAttributedText:(NSAttributedString *)attributedText forKey:(NSString *)aKey 富文本排列方式无法设置

### ISSUE THREAD

**Issue by lzcdgit** [svga/SVGAPlayer-iOS#59]
- (void)setAttributedText:(NSAttributedString *)attributedText forKey:(NSString *)aKey;
替换文字的方法，富文本排列方式无法设置 代码如下。

  NSMutableParagraphStyle *paragraphStyle =  [[NSMutableParagraphStyle alloc] init];
    paragraphStyle.alignment = NSTextAlignmentCenter;
    
    NSMutableAttributedString *text2 = [[NSMutableAttributedString alloc] initWithString:toNickname attributes:@{NSForegroundColorAttributeName:white_color,NSFontAttributeName: [UIFont boldSystemFontOfSize:15],NSParagraphStyleAttributeName:paragraphStyle}];

    [self.aPlayer setAttributedText:text2 forKey:@"Bitmap7"];
    
富文本无法居中

**Comment by PonyCui** [comment]
动态文本默认就是居中的

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-iOS/commit/53fa6e051c6dc8e49f052f28e53cd8929ab66662
