### ISSUE TITLE
播放不同的svga内存持续增加问题

### ISSUE THREAD

**Issue by ztlight000** [svga/SVGAPlayer-iOS#6]
我本地播放不同的svga文件，内存会持续增加，感觉像是有缓存，请问怎么解决这个问题？

**Comment by PonyCui** [comment]
NSCache 会在内存不足时，自动释放，不需要担心。

**Comment by pengxu1013** [comment]
亲测内存会增加,怎么解决?

**Comment by voshk** [comment]
> 亲测内存会增加,怎么解决?
SVGAVideoEntity不使用saveCache或者不想改动代码就在SVGAParser的enabledMemoryCache设置为NO使用weakCache。只要不使用NSCache，内存就不会持续增加了。虽然目前还在观察enabledMemoryCache为NO有什么不好的情况 ：）

**Comment by voshk** [comment]
> 亲测内存会增加,怎么解决?


SVGAParser的enabledMemoryCache设置为NO使用weakCache

**Comment by voshk** [comment]
> 亲测内存会增加,怎么解决?

SVGAVideoEntity不使用saveCache就可以了。或者不想改代码的话，
SVGAParser的enabledMemoryCache设置为NO使用weakCache，不使用NSCache内存就不会持续增长了。虽然目前还在观察enabledMemoryCache设置为NO会有什么不好的影响 ：）
