### ISSUE TITLE
clearsAfterStop default value

### ISSUE THREAD

**Issue by SummitXY** [svga/SVGAPlayer-iOS#65]
## Problem 
In [Wiki](https://github.com/yyued/SVGAPlayer-iOS/wiki/APIs) the `SVGAPlayer` property  `clearsAfterStop` default value is `YES`, but actually the default value is `NO`(as it is BOOL and not initialized somewhere else).

**Comment by PonyCui** [comment]
Emm, it's a issue! Really~ I'll fix it ASAP.

**Comment by errnull** [comment]
Already fixed cb99a0b
