### ISSUE TITLE
crash while network respone data is empty

### ISSUE THREAD

**Issue by enefry** [svga/SVGAPlayer-iOS#66]
## Attention

-[_NSZeroData subdataWithRange:]: range {0, 4} exceeds data length 0
 Handle Exception: Exception Name: NSRangeException
Exception Reason: *** -[_NSZeroData subdataWithRange:]: range {0, 4} exceeds data length 0

Thread 3 (crashed)
 0  CoreFoundation!__exceptionPreprocess + 0xe4
    Found by: given as instruction pointer in context
 1  libobjc.A.dylib!objc_exception_throw + 0x34
    Found by: previous frame's frame pointer
 2  CoreFoundation!+[NSException raise:format:] + 0x70
    Found by: previous frame's frame pointer
 3  Foundation!-[NSData(NSData) subdataWithRange:] + 0xf8
    Found by: previous frame's frame pointer
 4  !-[SVGAParser parseWithData:cacheKey:completionBlock:failureBlock:] [SVGAParser.m : 187 + 0x14]
    Found by: previous frame's frame pointer
 5  !__63-[SVGAParser parseWithURLRequest:completionBlock:failureBlock:]_block_invoke.43 [SVGAParser.m : 60 + 0x1c]
    Found by: previous frame's frame pointer
 6  CFNetwork!__75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 0x1c
    Found by: previous frame's frame pointer
 7  CFNetwork!__49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 0xac
    Found by: previous frame's frame pointer
 8  Foundation!__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 0xc
    Found by: previous frame's frame pointer
 9  Foundation!-[NSBlockOperation main] + 0x44
    Found by: previous frame's frame pointer
10  Foundation!-[__NSOperationInternal _start:] + 0x2e0
    Found by: previous frame's frame pointer
11  Foundation!__NSOQSchedule_f + 0x10c
    Found by: previous frame's frame pointer
12  libdispatch.dylib!_dispatch_call_block_and_release + 0x14
    Found by: previous frame's frame pointer
13  libdispatch.dylib!_dispatch_client_callout + 0xc
    Found by: previous frame's frame pointer
14  libdispatch.dylib!_dispatch_continuation_pop$VARIANT$mp + 0x198
    Found by: previous frame's frame pointer
15  libdispatch.dylib!_dispatch_async_redirect_invoke + 0x310
    Found by: previous frame's frame pointer
16  libdispatch.dylib!_dispatch_root_queue_drain + 0x170
    Found by: previous frame's frame pointer
17  libdispatch.dylib!_dispatch_worker_thread2 + 0x7c
    Found by: previous frame's frame pointer
18  libsystem_pthread.dylib!_pthread_wqthread + 0x1cc
    Found by: previous frame's frame pointer
19  libsystem_pthread.dylib!start_wqthread + 0x0
    Found by: previous frame's frame pointer

- (void)parseWithData:(nonnull NSData *)data
             cacheKey:(nonnull NSString *)cacheKey
      completionBlock:(void ( ^ _Nullable)(SVGAVideoEntity * _Nonnull videoItem))completionBlock
         failureBlock:(void ( ^ _Nullable)(NSError * _Nonnull error))failureBlock {
    SVGAVideoEntity *cacheItem = [SVGAVideoEntity readCache:cacheKey];
    if (cacheItem != nil) {
        if (completionBlock) {
            [[NSOperationQueue mainQueue] addOperationWithBlock:^{
                completionBlock(cacheItem);
            }];
        }
        return;
    }

**Comment by PonyCui** [comment]
Use a new version to solve this issue.
