### ISSUE TITLE
svga不支持保存本地功能

### ISSUE THREAD

**Issue by elmaLin** [svga/SVGAPlayer-iOS#67]
想请问一下，SVGA能开发保存本地功能吗？目前只发现保存在缓存，每次重现打开APP都要重新下载SVGA，而且你们项目下载后居然用随机数保存在temp文件，根本找不出来，希望能提供这样的功能

**Comment by PonyCui** [comment]
使用 2.0 格式，不用解压到 temp 即可播放。
另外缓存的问题可以参考 https://github.com/yyued/SVGAPlayer-iOS#cache
SVGAPlayer 会借助 NSURLSession 管理文件缓存
