### ISSUE TITLE
Demo失效

### ISSUE THREAD

**Issue by zy414266852** [svga/SVGAPlayer-iOS#68]
只有matte.svga还可以播放 ，其他 Error Domain=SVGAParser Code=404 "File not exist." UserInfo={NSLocalizedDescription=File not exist.}

**Comment by zy414266852** [comment]
还有这种
UTF-8 failure, is some field type 'string' when it should be 'bytes'?
Error Domain=NSFilePath Code=-1 "(null)"

**Comment by PonyCui** [comment]
感谢指正，因为协议改动原因，导致问题存在，已经修正。
