### ISSUE TITLE
除以0的错误

### ISSUE THREAD

**Issue by nth2222** [svga/SVGAPlayer-iOS#71]
```
- (void)startAnimation {
    [self stopAnimation:NO];
    self.loopCount = 0;
    self.displayLink = [CADisplayLink displayLinkWithTarget:self selector:@selector(next)];
    self.displayLink.frameInterval = 60 / self.videoItem.FPS;
...
}
```

 self.videoItem.FPS maybe 0 then throw error io_thread_0 (1): EXC_ARITHMETIC (code=EXC_I386_DIV, subcode=0x0)

**Comment by PonyCui** [comment]
FPS can not be 0 unless SVGA file invalid,

**Comment by nth2222** [comment]
aready happened

**Comment by PonyCui** [comment]
First, ensure videoItem not nil, second ensure svga file valid.

**Comment by bluerainxty** [comment]
i met the problem，too

**Comment by Jiuaim** [comment]
Me too.

**Comment by yangqingren** [comment]
hi, FPS is 0, the SVGA file exported by AE or Flash? 
SVGA can u update it here , we will check it as soon as possible @nth2222  @bluerainxty @Jiuaim

**Comment by yangqingren** [comment]
fps fault-tolerant in 2.5.4
