### ISSUE TITLE
iOS13 Beta 版适配问题

### ISSUE THREAD

**Issue by dongfanggugu** [svga/SVGAPlayer-iOS#73]
iOS13 Beta 版适配，发现svga动画无法正常播放，svga中的资源没有加载出来。

**Comment by PonyCui** [comment]
暂时不会为 iOS 13 Beta 适配，如果在公开 Beta 版本仍有问题，再作处理。

**Comment by PonyCui** [comment]
使用 2.3.4 版本

**Comment by zhipengbird** [comment]
在iOS13版本上使用2.3.4版本同样无法正常播放

**Comment by PonyCui** [comment]
@zhipengbird 是否可以提供一个 Demo?

**Comment by zhipengbird** [comment]
使用xcode 10.4编译的工程，在iOS13上运行，SVGA就会展示异常
下面这个动画就很明显
https://static.starmakerstudios.com/production/statics/horse/horse_movie_20180824085110.svga

**Comment by PonyCui** [comment]
@errnull 看一下问题

**Comment by errnull** [comment]
> 使用xcode 10.4编译的工程，在iOS13上运行，SVGA就会展示异常
> 下面这个动画就很明显
> https://static.starmakerstudios.com/production/statics/horse/horse_movie_20180824085110.svga

iOS 13 的适配问题请见

**Comment by errnull** [comment]
> > 使用xcode 10.4编译的工程，在iOS13上运行，SVGA就会展示异常
> > 下面这个动画就很明显
> > https://static.starmakerstudios.com/production/statics/horse/horse_movie_20180824085110.svga
> 
> iOS 13 的适配问题请见
https://juejin.im/post/5d47d1f2f265da03b31bb2e6
可以拉取最新的 master 分支代码测试。
