### ISSUE TITLE
内存暴涨,不释放怎么解决?

### ISSUE THREAD

**Issue by pengxu1013** [svga/SVGAPlayer-iOS#74]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by pengxu1013** [comment]
播放第一个svga文件时内存会涨到一个值且不下降,继续播放有时候徽章有时候又会降下去,总体是上涨趋势,请问是什么原因,该怎么释放内存?

**Comment by CHEN-TA0** [comment]
> 播放第一个svga文件时内存会涨到一个值且不下降,继续播放有时候徽章有时候又会降下去,总体是上涨趋势,请问是什么原因,该怎么释放内存?

我也遇到了，加载一个链接的svga文件（2M左右），内存会涨30M左右。
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/30544952/61795598-5cde3e00-ae56-11e9-90d1-775f37b2ea79.png">

**Comment by PonyCui** [comment]
https://www.zcool.com.cn/article/ZOTk0ODk2.html
