### ISSUE TITLE
[SVGAParser zlibinflate:] crash

### ISSUE THREAD

**Issue by tanqi2011** [svga/SVGAPlayer-iOS#75]
![exc_bad_access](https://user-images.githubusercontent.com/10671837/61573910-f7eab700-aae8-11e9-9ad5-f475e70f42ec.png)
![strm_object](https://user-images.githubusercontent.com/10671837/61573914-fcaf6b00-aae8-11e9-9cec-284e6b877a55.png)

crash的地方如图，其中NSlog、try-catch-finally代码是Debug的时候加上的，去掉即最新版本(2.3.3)代码。

![bugly](https://user-images.githubusercontent.com/10671837/61573905-ec978b80-aae8-11e9-994d-d13ab90134db.png)

上图是bugly收集到的crash。

**Comment by errnull** [comment]
> ![exc_bad_access](https://user-images.githubusercontent.com/10671837/61573910-f7eab700-aae8-11e9-9ad5-f475e70f42ec.png)
> ![strm_object](https://user-images.githubusercontent.com/10671837/61573914-fcaf6b00-aae8-11e9-9cec-284e6b877a55.png)
> 
> crash的地方如图，其中NSlog、try-catch-finally代码是Debug的时候加上的，去掉即最新版本(2.3.3)代码。
> 
> ![bugly](https://user-images.githubusercontent.com/10671837/61573905-ec978b80-aae8-11e9-994d-d13ab90134db.png)
> 
> 上图是bugly收集到的crash。

你好，方便提供一下相关的 .svga 文件用于定位问题吗？
可以将资源发送到 help@svga.io ,我们会尽快处理，并且保护版权不做他用。
@tanqi2011

**Comment by tanqi2011** [comment]
![image](https://user-images.githubusercontent.com/10671837/65215151-149e6d80-dadf-11e9-8a29-1ffdabe46906.png)
抱歉，这里定位不到相关的.svga文件。
异步线程下，只能看到这样的一个现象：我怀疑是解码的data对象在某一时刻被清空，但对应的线程还在处理这个data对象的原因。是否需要在此处添加data为nil的判断进行过滤？

**Comment by errnull** [comment]
![屏幕快照2019-09-23上午8 52 43](https://user-images.githubusercontent.com/28481578/65397080-87f5f700-dddf-11e9-9f35-ff0a4e51841e.png)
相关方法在处理 data 之前有进行空判断哦。
@tanqi2011

**Comment by errnull** [comment]
responding timeout.
please reopen the issue and provide more info.

**Comment by tanqi2011** [comment]
![crash device](https://user-images.githubusercontent.com/10671837/66743989-d2820500-eead-11e9-8024-dbb1471341d8.png)

不好意思，在赶项目。
这是目前收集到的bug设备分析，可以说大概率是在iOS8系统下出现的问题。

https://stackoverflow.com/questions/30140318/nsblockoperation-exc-bad-access
参考到一篇文章，是针对___NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__这个错误的。
希望对您有帮助！

**Comment by wuxie8** [comment]
现在这个问题有解决方案吗？
