### ISSUE TITLE
有些svga文件 占用内存很大

### ISSUE THREAD

**Issue by xiaohuihui000** [svga/SVGAPlayer-iOS#79]
我有个svga文件是1M多的，播放的时候消耗手机内存800M，这个问题能处理吗

**Comment by PonyCui** [comment]
把这篇文章丢给设计师
https://www.zcool.com.cn/article/ZOTk0ODk2.html
然后告诉设计师，导出工具里明确告知你内存占用超过8M，可能导致目标应用崩溃，为什么还要把文件丢给工程师使用。

**Comment by xiaohuihui000** [comment]
我们设计说 只有一帧的svga导出 也会提示超出8M，但是导出的文件是小于8M的

**Comment by xiaohuihui000** [comment]
[svga.zip](https://github.com/yyued/SVGAPlayer-iOS/files/3574220/svga.zip)
这是那个svga文件  里面资源是比其他的多

**Comment by PonyCui** [comment]
PSD 导入的时候，要正确选择选项。
<img width="367" alt="请在导入时使用此模式" src="https://user-images.githubusercontent.com/5013664/64251932-337ffa00-cf4c-11e9-869f-516d1263b31b.png">
