### ISSUE TITLE
Loading a big special effect takes a lot of time, which leads to a 100% increase in CPU.

### ISSUE THREAD

**Issue by ywx372421496** [svga/SVGAPlayer-iOS#80]
'SVGAPlayer', '~> 2.1.4'
This place takes too much time under this version.
Question points:
UIImage *image = [[UIImage alloc] initWithData:protoImages[key] scale:2.0];

**Comment by errnull** [comment]
Thank's for your feedfack

**Comment by errnull** [comment]
> 'SVGAPlayer', '~> 2.1.4'
> This place takes too much time under this version.
> Question points:
> UIImage *image = [[UIImage alloc] initWithData:protoImages[key] scale:2.0];

Thank's for your feedback
Could you please provide more info just like a demo or
the code block.

**Comment by errnull** [comment]
@ywx372421496

**Comment by ywx372421496** [comment]
> @ywx372421496



> > 'SVGAPlayer', '~> 2.1.4'
> > This place takes too much time under this version.
> > Question points:
> > UIImage *image = [[UIImage alloc] initWithData:protoImages[key] scale:2.0];
> 
> Thank's for your feedback
> Could you please provide more info just like a demo or
> the code block.

Sorry, I didn't find this problem in the demo. It should be related to my project.
thank you

**Comment by ywx372421496** [comment]
> > 'SVGAPlayer', '~> 2.1.4'
> > This place takes too much time under this version.
> > Question points:
> > UIImage *image = [[UIImage alloc] initWithData:protoImages[key] scale:2.0];
> 
> Thank's for your feedback
> Could you please provide more info just like a demo or
> the code block.

Sorry, no problem with the demo, it has something to do with my project.
thank you.

**Comment by ywx372421496** [comment]
> > 'SVGAPlayer', '~> 2.1.4'
> > This place takes too much time under this version.
> > Question points:
> > UIImage *image = [[UIImage alloc] initWithData:protoImages[key] scale:2.0];
> 
> Thank's for your feedback
> Could you please provide more info just like a demo or
> the code block.

I found an svga, and the CPU was really high when I played it. You can try it.
The following：
[4C37D3E7FF9D3ADD15260089CE93BC09.svga.zip](https://github.com/yyued/SVGAPlayer-iOS/files/3549781/4C37D3E7FF9D3ADD15260089CE93BC09.svga.zip)

**Comment by PonyCui** [comment]
动画看上去有点复杂，尝试使用 15 FPS 重新导出这个动画看看。

**Comment by ywx372421496** [comment]
> 动画看上去有点复杂，尝试使用 15 FPS 重新导出这个动画看看。

动画 15 FPS的话，将了些，首针在85%左右


[4C37D3E7FF9D3ADD15260089CE93BC10.svga.zip](https://github.com/yyued/SVGAPlayer-iOS/files/3554359/4C37D3E7FF9D3ADD15260089CE93BC10.svga.zip)


这样的话，帧数要做限制吗？能优化吗？谢谢

**Comment by PonyCui** [comment]
已经 OK 了，主要是你这个动画素材有点多，Image 解码占用高是肯定了，也没有能继续优化的地方。

**Comment by ywx372421496** [comment]
> 已经 OK 了，主要是你这个动画素材有点多，Image 解码占用高是肯定了，也没有能继续优化的地方。

好的，谢谢

**Comment by errnull** [comment]
Have to fixed.
