### ISSUE TITLE
What are the advantages of 2.0.0 svga?

### ISSUE THREAD

**Issue by liuqimother** [svga/SVGAPlayer-iOS#82]
1.Decompression using zlib
2.Less data, faster parsing

Anyother advantages？

**Comment by errnull** [comment]
> 1.Decompression using zlib
> 2.Less data, faster parsing
> 
> Anyother advantages？

Here are the CHANGELOG for the advantages of 2.0.0 SVGAPlayer-iOS
https://github.com/yyued/SVGAPlayer-iOS/blob/master/CHANGELOG.md
@liuqimother

**Comment by errnull** [comment]
responding timeout.
please reopen the issue and provide more info.
