### ISSUE TITLE
Can i submit code to this project?

### ISSUE THREAD

**Issue by liuqimother** [svga/SVGAPlayer-iOS#83]
Modifier List:
1.Support change the save position of svga
2.Support custom save the svga2.0.0 file to disk not nsurlsession
3.Supply new api for getcachekeybyurl
4.Supply new api for release the cache in player,not nscache
5.Support change the textlayer's alignmentMode
6.Supply new api for remove the cache by url

**Comment by errnull** [comment]
> Modifier List:
> 1.Support change the save position of svga
> 2.Support custom save the svga2.0.0 file to disk not nsurlsession
> 3.Supply new api for getcachekeybyurl
> 4.Supply new api for release the cache in player,not nscache
> 5.Support change the textlayer's alignmentMode
> 6.Supply new api for remove the cache by url

Okay, thanks for your attention,
of course, you can commit your change with pull request，
we will review it ASAP.
@liuqimother

**Comment by errnull** [comment]
responding timeout.
please reopen the issue and provide more info.
