### ISSUE TITLE
播放结束的代理再debug版本和release版本有什么不同吗？

### ISSUE THREAD

**Issue by Resoulte** [svga/SVGAPlayer-iOS#84]
我再基类里面遵守代理，然后各个子控制器分别处理代理事件，再debug版本下没问题，再release版本下却不走动画结束的代理

**Comment by liuqimother** [comment]
no difference

**Comment by errnull** [comment]
> 我再基类里面遵守代理，然后各个子控制器分别处理代理事件，再debug版本下没问题，再release版本下却不走动画结束的代理

测试了  master 分支 & Pod SVGAPlayer (2.3.4)
![屏幕快照2019-09-02下午5 53 13](https://user-images.githubusercontent.com/28481578/64106795-7fe00400-cdab-11e9-948c-f2a2272f2d92.png)
均有结束回调，确认动效循环 loops 不是 0 动效循环播放的时候是不会触发 finished 的。
@Resoulte

**Comment by errnull** [comment]
responding timeout.
please reopen the issue and provide more info.
