### ISSUE TITLE
缓存 问题 

### ISSUE THREAD

**Issue by xiaohuihui000** [svga/SVGAPlayer-iOS#85]
我看了内部代码 每次都要去下载， 为什么没把下载的数据缓存起来 下次一看有了 就不用下载了

**Comment by PonyCui** [comment]
https://github.com/yyued/SVGAPlayer-iOS#cache

**Comment by PonyCui** [comment]
对于缓存，开发者可自行实现，Player 专注于播放，而非资源管理。

**Comment by xiaohuihui000** [comment]
我自己做了缓存  把每次下载的数据 都缓存到了本地 下次直接用 有时候会播放失败

经过查找发现 有的svga头文件信息是 504b0304 为什么有的svga文件会被认为是zip 格式的呢

**Comment by errnull** [comment]
目前用于解析的 .svga 文件只有两种可能，
1. 2.x 的二进制文件。
2. 1.x 的压缩文件。

https://filesignatures.net/index.php?page=search&search=504B0304&mode=SIG
非 504B0304 据此判断为非 zip 文件。
@xiaohuihui000

播放失败的样本能不能发送一份到 help@svga.io 方便排查问题。
这边会保护版权不做他用。

**Comment by xiaohuihui000** [comment]
我播放失败 的原因是因为 是压缩文件 我把他当成二进制文件处理了

**Comment by xiaohuihui000** [comment]
我们设计给的svga 为什么有的是2.x的二进制文件 ，有的是1.x的压缩文件，

**Comment by errnull** [comment]
> 我们设计给的svga 为什么有的是2.x的二进制文件 ，有的是1.x的压缩文件，
> 我播放失败 的原因是因为 是压缩文件 我把他当成二进制文件处理了

1.x 是最初的 svga 版本，后来为了提升解析速度迭代了 2.x 二进制描述文件。
虽然现在 Player 向下兼容 1.x, 但我们还是非常建议使用新的 2.x 格式，
你可以让设计师重新导出 2.x 文件给你。

Parser 会自动识别 1.x 压缩文件和 2.x ，
正常情况下不会有异常的，如果播放失败有可能是 .svga 文件本身有问题。
@xiaohuihui000

**Comment by xiaohuihui000** [comment]
我们设计想问下 导出svga的时候 实际没有超出8M 但是提示了超出8M的弹框 为什么呢

**Comment by errnull** [comment]
> 我们设计想问下 导出svga的时候 实际没有超出8M 但是提示了超出8M的弹框 为什么呢
http://svga.io/svga-preview.html
浏览动画，查看素材，
这里的 8M 限制主要是说素材解压后占用的内存。
@xiaohuihui000

**Comment by errnull** [comment]
将会提供缓存更新机制
