### ISSUE TITLE
ios 13 

### ISSUE THREAD

**Issue by xiaohuihui000** [svga/SVGAPlayer-iOS#86]
我更新了2.3.4，在iOS13下 还是有些资源显示不出来
手机是ipod 
svga是
[406.svga.zip](https://github.com/yyued/SVGAPlayer-iOS/files/3593989/406.svga.zip)

**Comment by errnull** [comment]
> 我更新了2.3.4，在iOS13下 还是有些资源显示不出来
> 手机是ipod
> svga是
> [406.svga.zip](https://github.com/yyued/SVGAPlayer-iOS/files/3593989/406.svga.zip)

看了一下你这个动效素材解码出来有 33M 之多，
一般建议不超过 8 M ，可以适当优化素材尺寸。
![屏幕快照2019-09-16下午2 30 48](https://user-images.githubusercontent.com/28481578/64937967-d90d6480-d88e-11e9-85e1-85a43ba0247a.png)

动效能够正常播放，说明 parse & play 流程能够走通，
缺失的部分元素可能是导出失败，
麻烦你将显示不出来的资源标注一下。
@xiaohuihui000

**Comment by xiaohuihui000** [comment]
我这里有个小于8M的svga文件，在13系统上部分元素还是会导出失败，导出失败的资源是img_6
![20190916163555](https://user-images.githubusercontent.com/24727182/64944131-30680080-d8a0-11e9-93d1-343712ee45fd.jpg)

SVGA文件是
[口红.svga.zip](https://github.com/yyued/SVGAPlayer-iOS/files/3615304/svga.zip)


还有一个问题 ，比如上面的这个svga文件是一个很简单的动画就达到了4M，怎么才能把一个非常复杂的动画缩小到8M以下

**Comment by errnull** [comment]
导出失败不是 iOS 13 的问题，
Converter 在导出的时候元素不正常，自然播放不了。

可以麻烦把 .aep 源文件发送到 help@svga.io 吗？这边排查一下问题。
我们会保护源文件不做他用 。
@xiaohuihui000

**Comment by objChen** [comment]
我也遇到了同样的问题在iOS13 ，出问题的svga似乎都是图片宽高较大的没有加载出来，v2.3.4的SVGAVideoEntity中虽然改为containsString方式判断，但是在iOS13 data为OS_dispatch_data，不知道是不是这个原因导致转image失败

**Comment by objChen** [comment]
同一个svga文件，非iOS13都是完全正常的

**Comment by xiaohuihui000** [comment]
@errnull 邮件发送了 麻烦接收下

你说失败不是13的问题，可是在13以下的系统上 都能正常播放

**Comment by errnull** [comment]
> 我也遇到了同样的问题在iOS13 ，出问题的svga似乎都是图片宽高较大的没有加载出来，v2.3.4的SVGAVideoEntity中虽然改为containsString方式判断，但是在iOS13 data为OS_dispatch_data，不知道是不是这个原因导致转image失败

你好，我在
iPhone XR iOS 13 beta 5 
Xcode 11 GM seed

中使用 SVGAPlayer-iOS 源码 demo 播放动效，
似乎没有异常
可以麻烦你提供一个 demo 我这边尝试一下吗？
@objChen

**Comment by luohaiquan** [comment]
我也遇到了这个问题，已经更新了2.3.4，iOS13系统本来还能播的一个动画，iOS13.1播不出来了，http://pws.myhug.cn/static/svga/liuxingyujinchang.svga

**Comment by lixiaonan** [comment]
老哥, 我也遇到了这个问题

**Comment by PonyCui** [comment]
升级到 2.3.5 解决问题，具体问题原因稍后 @errnull 会通过另一个 issue 说明。

**Comment by errnull** [comment]
See #95
