### ISSUE TITLE
head里设置了etag 但是每次都会重新请求数据

### ISSUE THREAD

**Issue by sum123** [svga/SVGAPlayer-iOS#88]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by sum123** [comment]
http://bjyoudian.oss-cn-beijing.aliyuncs.com/img%2Fgift%2Fheartbeat_full_v3.svga?Expires=7857648000&OSSAccessKeyId=LTAIehsZuPH8HTaR&Signature=gqpIb4i3jtXPR72QHJrp20P3OyU%3D

**Comment by sum123** [comment]
另外，如何做本地缓存 有demo么

**Comment by xiaohuihui000** [comment]
@Sum123 
我做了本地缓存 给你提供下思路 你参考下
播放的时候 先根据url校验本地是否有数据，有播放
没有下载，下载播放后 前几个字节不是504b0304的二进制 写本地

**Comment by Best199101** [comment]
Has the caching mechanism been added ?

**Comment by zhixingxi** [comment]
> @Sum123
> 我做了本地缓存 给你提供下思路 你参考下
> 播放的时候 先根据url校验本地是否有数据，有播放
> 没有下载，下载播放后 前几个字节不是504b0304的二进制 写本地

嗨，本地缓存的代码可以分享一下吗？谢谢！

**Comment by 20120608** [comment]
自己把nsdata缓存起来吧
`
SVGAParser *parser = [[SVGAParser alloc] init];
        
        NSMutableURLRequest *URLRequest = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:minstr([giftData valueForKey:@"swf"])]];
        URLRequest.cachePolicy = NSURLRequestReturnCacheDataElseLoad;
        
        /// 获取文件
        // 参数1: 文件路径
        // 参数2: 在那个文件夹系统下进行索引这个路径
        // 参数3: YES绝对路径/NO相对路径
        NSString *fileStr = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES)lastObject];
       
       
        NSArray *tempArr = [minstr([giftData valueForKey:@"swf"]) componentsSeparatedByString:@"/"];
        NSString *name;
        if ([tempArr lastObject] != nil) {
            NSArray *tempArr2 = [[tempArr lastObject] componentsSeparatedByString:@","];
            name = [tempArr2 firstObject];
        }
        NSString *dataPath = [fileStr stringByAppendingString:[NSString stringWithFormat:@"/%@",name]];

        
        NSData *resultData = [NSData dataWithContentsOfFile:dataPath];
        if (resultData) {
            NSLog(@"缓存存在!!!!!!!!!");
            [parser parseWithData:resultData cacheKey:[self cacheKey:URLRequest.URL] completionBlock:^(SVGAVideoEntity * _Nonnull videoItem) {
                [[NSOperationQueue mainQueue] addOperationWithBlock:^{
                    gifView = [[exoensiveGifGiftV alloc]initWithGiftData:giftData andVideoitem:videoItem];
                    [self addSubview:gifView];
                    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(seconds * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                        [gifView removeFromSuperview];
                        [self sethaohuacount];
                        if (_expensiveGiftCount.count >0) {
                            [self.delegate expensiveGiftdelegate:nil];
                        }
                    });
                }];
            } failureBlock:^(NSError * _Nonnull error) {
                
            }];

            
        } else {
            [[[NSURLSession sharedSession] dataTaskWithRequest:URLRequest completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
                if (error == nil && data != nil) {
                     // NSData 对象写入文件
                    // 构建二进制文件的存储路径
                    // 将内容写入文件
                    // 参数1: 文件路径
                    // 参数2: 是否原子保护
                    [data writeToFile:dataPath atomically:YES];
                    
                    [parser parseWithData:data cacheKey:[self cacheKey:URLRequest.URL] completionBlock:^(SVGAVideoEntity * _Nonnull videoItem) {
                        [[NSOperationQueue mainQueue] addOperationWithBlock:^{
                            gifView = [[exoensiveGifGiftV alloc]initWithGiftData:giftData andVideoitem:videoItem];
                            [self addSubview:gifView];
                            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(seconds * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                                [gifView removeFromSuperview];
                                [self sethaohuacount];
                                if (_expensiveGiftCount.count >0) {
                                    [self.delegate expensiveGiftdelegate:nil];
                                }
                            });
                        }];
                    } failureBlock:^(NSError * _Nonnull error) {
                        
                    }];
                }
                else {
                    
                }
            }] resume];
        }

`
