### ISSUE TITLE
SVGAPlayer-iOS 2.1.0 发现每次都会请求不走缓存是为什么? 

### ISSUE THREAD

**Issue by JasonStu** [svga/SVGAPlayer-iOS#9]
您好!

       我在iosdebug 环境看到fileExistsAtPath 每次都都是false 并不走缓存 我看到你close 的一个相同的问题说打到max-cache 就会缓存 我下面的链接已经打到了 3.6M 了 

       (https://ele-production.nos-eastchina1.126.net/uploads/nil_class/6bbe7b8c2695517de5dccd2f9764415a.svga)这是我做的svga

- (void)parseWithURL:(nonnull NSURL *)URL
     completionBlock:(void ( ^ _Nonnull )(SVGAVideoEntity * _Nullable videoItem))completionBlock
        failureBlock:(void ( ^ _Nullable)(NSError * _Nullable error))failureBlock {
// 不会走缓存
    if ([[NSFileManager defaultManager] fileExistsAtPath:[self cacheDirectory:[self cacheKey:URL]]]) {
        [self parseWithCacheKey:[self cacheKey:URL] completionBlock:^(SVGAVideoEntity * _Nonnull videoItem) {
            if (completionBlock) {
                completionBlock(videoItem);
            }
        } failureBlock:^(NSError * _Nonnull error) {
            [self clearCache:[self cacheKey:URL]];
            if (failureBlock) {
                failureBlock(error);
            }
        }];
        return;
    }
    [[[NSURLSession sharedSession] dataTaskWithURL:URL completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {
//每次都会进行请求 
        if (error == nil && data != nil) {
            [self parseWithData:data cacheKey:[self cacheKey:URL] completionBlock:^(SVGAVideoEntity * _Nonnull videoItem) {
                if (completionBlock) {
                    completionBlock(videoItem);
                }
            } failureBlock:^(NSError * _Nonnull error) {
                [self clearCache:[self cacheKey:URL]];
                if (failureBlock) {
                    failureBlock(error);
                }
            }];
        }
        else {
            if (failureBlock) {
                failureBlock(error);
            }
        }
    }] resume];
}

**Comment by PonyCui** [comment]
SVGAParser 遵从 iOS NSURLProtocol 默认的缓存规则

**Comment by PonyCui** [comment]
fileExistsAtPath 只为 1.x format 兼容使用，请忽略。
