### ISSUE TITLE
After phone update iOS13, original SVGA may not be able to play, on the old version (12.3.1) model can display normally

### ISSUE THREAD

**Issue by ilife-x** [svga/SVGAPlayer-iOS#92]
## Attention

* Do not ask any usage question, issue board is a issue board, accept library bugs only.
* If you are facing any usage problem, read the README again.

## Issue Template

Issue Description(What's your problem)

How To Reappear(How to reappear the issue)

Any Attachment(Provide a sample about your issue)

------ 中文分割线 ------

## 注意 

* 不要在 Issue 板块提问使用问题，Issue 板块只接受 Bug 反馈。
* 如果遇到使用上的问题，仔细阅读 README。

## Issue 模板

请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

**Comment by ilife-x** [comment]
Pod is updated and ready to display

**Comment by easoncodes** [comment]
Hi, It‘s the issue fixed?

**Comment by PonyCui** [comment]
升级到 2.3.5 解决问题，具体问题原因稍后 @errnull 会通过另一个 issue 说明。

**Comment by errnull** [comment]
See #95
