### ISSUE TITLE
iOS 13 解析大图异常请升级  V2.3.5 解决

### ISSUE THREAD

**Issue by errnull** [svga/SVGAPlayer-iOS#95]
https://juejin.im/post/5d47d1f2f265da03b31bb2e6

**Comment by errnull** [comment]
https://juejin.im/post/5d47d1f2f265da03b31bb2e6

**Comment by errnull** [comment]
iOS 13 parsing picture exception, please upgrade V2.3.5.

**Comment by objChen** [comment]
![屏幕快照 2019-10-12 下午4 02 33](https://user-images.githubusercontent.com/37887715/66697622-06242a00-ed0a-11e9-8986-edf286d3595b.png)

**Comment by errnull** [comment]
使用 `pod update`
![屏幕快照2019-10-14下午3 00 36](https://user-images.githubusercontent.com/28481578/66733824-64304900-ee93-11e9-93ce-026c59eefbd9.png)
@objChen
