### ISSUE TITLE
以在私有库中添加依赖的方式导入项目后，编译报错，无法正常工作

### ISSUE THREAD

**Issue by MrBugDou** [svga/SVGAPlayer-iOS#97]
在私有库中添加依赖
s.dependency 'SVGAPlayer', '~> 2.3.5'

安装完成后只要导入头文件

#import <SVGAPlayer/SVGA.h>

像下图一样注释掉就可以编译通过，一打开就会出现下面的错误
![image](https://user-images.githubusercontent.com/12947653/66696110-855e3180-ecfb-11e9-8733-1fdbc8dd1218.png)

就会出现如下的报错

截图如下

![image](https://user-images.githubusercontent.com/12947653/66536346-26f45000-eb4f-11e9-9609-d847ec4372a8.png)

![image](https://user-images.githubusercontent.com/12947653/66536348-2a87d700-eb4f-11e9-8d02-307feef2ebc0.png)

这是Demo，还蛮烦您帮我看看应该怎么解决
[MyLibrary.zip](https://github.com/yyued/SVGAPlayer-iOS/files/3720270/MyLibrary.zip)

**Comment by errnull** [comment]
在 `MyLibrary.podspec` 中添加：
```
s.pod_target_xcconfig = {
    # This is needed by all pods that depend on Protobuf:
    'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1',
    # This is needed by all pods that depend on gRPC-RxLibrary:
    'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES'
  }

```
或者 `/MyLibrary/Example/Podfile`中去除：
```
#use_framworks!
```
可正常编译。
@MrBugDou

**Comment by JimmyGoGoGo** [comment]
我在本地库上加入以上的配置还是不行

**Comment by errnull** [comment]
这是方案1：
[MyLibrary_01.zip](https://github.com/yyued/SVGAPlayer-iOS/files/3737953/MyLibrary_01.zip)
这是方案 2：
[MyLibrary_02.zip](https://github.com/yyued/SVGAPlayer-iOS/files/3737955/MyLibrary_02.zip)
改完记得 `pod install`

@JimmyGoGoGo
