### ISSUE TITLE
设计师反应帧数太多时，转换成svga格式的动画，动画就不会动了，这个是什么原因呢？

### ISSUE THREAD

**Issue by zhang-yong-shuai** [svga/SVGAPlayer-iOS#98]

**Comment by PonyCui** [comment]
请提供 aep 及相关素材，以及导出的 svga 文件。

**Comment by PonyCui** [comment]
请尽量使用英文提交 Issue

请确切回答：问题的描述、重现方式、附件（提供一个 Demo 以重现问题）

请保证 issue 质量，如果没有合适的 issue 线索，该 issue 将被关闭。

**Comment by errnull** [comment]
你好可以提供相关的 .svga 文件吗？
需要脱敏的话可以把文件发到 help@svga.io，
我看了之后回复你，我们会有响应的保护措施。
@zhang-yong-shuai
